FROM docker.io/jleighsutherland/dream-base:v4

WORKDIR /app

COPY model /app/model

COPY gradio-serving.py /app/gradio-serving.py

RUN pip install -r model/requirements.txt

EXPOSE 7860

CMD ["python3", "gradio-serving.py", "--predicted-features", "['eod_market_data___mcd_us__open']", "--model-name", "model_example_z", "--model-serving-url", "http://model-example-z-api-service.mlserve-model-example-z.svc.cluster.local:5000/invocations"]